---
- name: 'Instala a lista de pacotes de dependencias'
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  loop:
    - mysql-server-8.0
    - python3-mysqldb

- name: 'Cria O banco de dados wordpressdb no MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: 'Crie o usuário do banco de dados com o nome wordpress_user com todos os privilégios do banco de dados'
  mysql_user:
    login_user: root
    name: "{{ wp_db_username }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  loop:
    - "{{ wp_network_range_ip }}"
  no_log: true

- name: 'Configura o MySQL para aceitar conexões remotas'
  copy:
    src: 'files/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: yes
  notify:
    - restart mysql