
Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/trusty64"

	config.vm.provider "virtualbox" do |vb|
		vb.name = "Ubuntu Wordpress 14.04.6 LTS"
		vb.memory = 1024
		vb.cpus = 1
	end
	
	config.vm.define "ansible" do |ansible|
		#ansible.name = "Ubuntu Ansible 14.04.6 LTS"
		ansible.vm.provider "virtualbox" do |vb|
			vb.name = "Ubuntu Ansible 14.04.6 LTS"
			vb.memory = 1024
			vb.cpus = 2
		end
		
		ansible.vm.network "public_network", ip: "170.10.110.10"
		
		ansible.vm.provision "shell",
			inline: "cp /vagrant/id_bionic  /home/vagrant && \
					 chmod 600 /home/vagrant/id_bionic && \
					 chown vagrant:vagrant /home/vagrant/id_bionic"

		ansible.vm.provision "shell",
			inline: "apt-get update && \
					 apt-get install -y software-properties-common && \
					 apt-add-repository --yes --update ppa:ansible/ansible && \
					 apt-get install -y ansible"
	end

	config.vm.define "wordpress" do |wordpress|
		wordpress.vm.network "private_network", ip: "170.10.110.11"
	end
	
	
end
