---
# End - Criando o servidor web - WordPress
- hosts: wordpress
  become: yes
  
  roles:
    - webserver
    - wordpress
# End - Criando o servidor web - WordPress


# Begin - Criando o servidor de banco de dados - MySQL
- hosts: database
  roles:
    - mysql    
  become: yes
# End - Criando o servidor de banco de dados - MySQL

...