
Vagrant.configure("2") do |config|
	
	config.vm.box = "ubuntu/focal64"
	
	# Criando a VM Wordpress
	config.vm.define "wordpress" do |wordpress|
		wordpress.vm.provider "virtualbox" do |vb|
			vb.name = "Ubuntu 20.04.3 LTS - Wordpress"
			vb.memory = 1024
			vb.cpus = 2
		end
		wordpress.vm.network "public_network", ip: "192.168.0.30"
		wordpress.vm.provision "shell", inline: "apt-get update && apt-get install -y net-tools"
		wordpress.vm.provision "shell", inline: "echo VM Ubuntu 20.04.3 LTS - Wordpress criada e pronta para uso."
	end	 


	# Criando a VM MySQL
	config.vm.define "mysql" do |mysql|
		mysql.vm.provider "virtualbox" do |vb|
			vb.name = "Ubuntu 20.04.3 LTS - MySQL-8"
			vb.memory = 1024
			vb.cpus = 2
		end
		mysql.vm.network "public_network", ip: "192.168.0.31"
		mysql.vm.provision "shell", inline: "apt-get update && apt-get install -y net-tools"
		mysql.vm.provision "shell", inline: "echo VM Ubuntu 20.04.3 LTS - MySQL-8 criada e pronta para uso."
	end

end