---
- name: 'Montar o Repo PHP 8.0'
  apt_repository:
    repo: ppa:ondrej/php

- name: 'Insta a lista de pacotes de dependencias'
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - software-properties-common
    - php8.0
    - apache2

- name: 'instalar pilha de pacotes'
  apt:
    pkg: "{{ item }}"
    state: present
  become: yes
  loop:
    - php8.0-mysql
    - php8.0-curl
    - php8.0-common
    - php8.0-cgi
    - php8.0-xsl
    - php8.0-cgi
    - php8.0-gd
    - php8.0-mbstring
    - php8.0-zip
    - php8.0-xmlrpc
    - php8.0-soap
    - php8.0-intl
    - libapache2-mod-php8.0
    - python3-pip
    - libmysqlclient-dev
    - python3-dev
