---
- name: 'Baixa o arquivo de instalação do WordPress'
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: 'Descompacta o Wordpress'
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www
    remote_src: yes
  become: yes

- name: 'Cria uma cópia do arquivomysqld.cnf wp-config-sample.php'
  copy:
    src: "{{ wp_instalation_dir }}/wp-config-sample.php"
    dest: "{{ wp_instalation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura o wp-config com os dados de acesso ao banco de dados'
  replace:
    path: "{{ wp_instalation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  loop:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_db_username }}"}
    - { regex: 'password_here', value: "{{ wp_db_password }}" }
    - { regex: 'localhost', value: "{{ wp_database_ip }}" }
  become: yes

#   - name: 'Configura o Apache para servir o Wordpress'
#     copy: 
#       src: 'files/000-default.conf'
#       dest: '/etc/apache2/sites-available/000-default.conf'
#     become: yes
#     notify:
#       - restart apache
  
- name: 'Configura o Apache para servir o Wordpress'
  template: 
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
    - restart apache